# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

### /chat
POST http://127.0.0.1:8000/chat
Content-Type:application/json

{
    "message": "用户有多少个"
}
